from . import Client
from typing import Dict, Optional, Any, List, Callable
from dataclasses import dataclass


@dataclass
class Turn:
    """ Represents one turn in a chat conversation."""
    name: str
    text: str


class Chat:

    def __init__(self, client: Client, names: List[str], contexts: List[str] = None, turns: Optional[List[Turn]] = None, settings: Optional[Dict[str, Any]]=None):
        """
        Creates a chat dialog similar to the OpenAI playground chat preset. Turns can be generated by open AI or
        added directly (as when a human being is responding). Turns do not have to follow any specific order.

        Args:
            client: A Client configured with an api key and a default_engine set.
            names: The names of the people in the chat. It is used to setup the stop tokens.
            context: Some optional text describing the scenario or individuals in the chat. Very helpful for the AI.
            turns: Some optional turns to show the bot the formatting and setup the rest of the conversation along with
                   the context. New turns will be appended to this list.
            settings: Overrides the default settings which are taken from the chat preset in the OpenAI playground.
        """

        self.client = client
        self.names = names
        self.contexts = contexts if contexts else []
        self.turns = turns if turns else []

        # Default settings from the chat preset in the OpenAI playground.
        self.settings = {
            'max_tokens': 150,
            'temperature': 0.9,
            'top_p': 1.0,
            'n': 1,
            'stream': False,
            'logprobs': 0,
            'stop': ['\n\n'] + [f'{name}:' for name in self.names]
        }

        # Override the defaults
        if settings:
            for key, val in settings.items():
                self.settings[key] = val

    def generate_turn(self, turn_name, post_gen_callback: Optional[Callable[[str, Dict], Optional[str]]] = None) -> Optional[Turn]:
        """
        Generates a dialog turn in the chat.

        Args:
            turn_name: The individual to generate a turn for. Should already exist in the 'names' property before
                generating.
            post_gen_callback: Optional callback that takes the generated response and returns the string to use as the
                turn text or None to cancel the turn completely.

        Returns:
            A Turn() representing the name and their generated text.

        """
        assert turn_name in self.names

        # Start the prompt with the context.
        prompt = "\n".join(self.contexts) + "\n\n"

        # Then add all the existing turns.
        for turn in self.turns:
            prompt += f"{turn.name}: {turn.text}\n\n"

        # Append the new turn to the prompt and send out a new completion request.
        prompt += f'{turn_name}:'
        self.settings['prompt'] = prompt
        response = self.client.completions(**self.settings)

        # Allow the callback to provide it's own text or choose from multiple options.
        if post_gen_callback:
            text = post_gen_callback(turn_name, response)
        else:
            # Otherwise we assume the first item in the list.
            assert len(response['choices']) > 0, "The list of choices returned from OpenAI was less than 1."
            text = response['choices'][0]['text']

        # If text ended up as None, consider it cancelled and don't continue to add it to the turn history.
        if text is None:
            return None

        # Create a new Turn using the text provided.
        assert type(text) == str
        turn = Turn(turn_name, text)

        # Save the this turn so we can reuse it as preamble on the next generation and return it.
        self.turns.append(turn)
        return turn
